name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: seeker
        run: |
          curl -v -k -o seeker-agent.zip "https://poc05.seeker.synopsys.com/rest/api/latest/installers/agents/binaries/JAVA"
          unzip seeker-agent.zip
          export MAVEN_OPTS="-javaagent:seeker-agent.jar -Dseeker.server.url=https://poc05.seeker.synopsys.com -Dseeker.project.key=webgoat-8 -Dseeker.access.token=9kmh3j0dud59t0ta5o9lpuf8nbufsao9vslip552tmmhkevdrd3g"
          mvn install -Dmaven.test.failure.ignore=true
   
   #- name: Polaris
   #     run: |
    #      curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
    #      unzip -d /tmp -jo polaris_cli-linux64.zip
   #       /tmp/polaris analyze -w
          
   #   - name: Black Duck
   #     run: |
   #       bash <(curl -s -L https://detect.synopsys.com/detect7.sh) --blackduck.url=https://poc18.blackduck.synopsys.com --blackduck.api.token=NTBiNDFlMmMtOWM0ZS00NTMyLThiZjMtMzc2ZTlhYWZiYzIzOjQyMGNjZDhjLTgzMTgtNGJhNi05YmY3LTA0NDg2MzIzNGQzNw== --detect.project.name=WebGoatDemo --detect.project.version.name=8.1
        
   
